// Anything you write is an Expression.
// For Eg."Divyesh" will not throw any error in the Js Program.

// Operators in Js

// Case 1 : Arithmetic Operators 

// let a = 25;
// let b = 21;
// console.log(a+b);
// console.log(a-b);
// console.log(a/b);
// console.log(a%b);
// console.log(a**2);
// console.log(++a);
// console.log(--a);

// Case 2 : Assignment Operators

// let a = 8;
// a+=5;
// console.log(a);

// Case 3 : Comparision Operators

// let a = 29;
// let b = "29";

// console.log(a==b); // This will return true even if the datatypes of the operands are different
// console.log(a!=b);

// console.log(a===b); // This will return true if the datatypes of the operands are same
// console.log(a!==b);


// Case 4 : Logical Operators 

// let x = 5;
// let y = 7;
// console.log(y>x && x==5)
// console.log(y>x || x==6)